messaging:
  url: nats://127.0.0.1:4222
  jetStream: true
  subscriptions:
    - name: agent-consumer
      topic: demo.start-task
      group: start-task
      pull: true
      ackWait: 5m
      endpoint:
        service: Agent
        method: start_task
    - name: agent-stop-tasks-consumer
      topic: demo.stop-tasks
      ackWait: 1h
      endpoint:
        service: Agent
        method: stop_tasks
